import { Supplier, ActivityLogItem } from '../types/supplier';

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'SUP-1001',
    name: 'Siemens Industrial Automation AG',
    taxId: 'DE-811124567',
    category: 'Industrial Machinery & Automation',
    country: 'Germany',
    countryCode: 'DE',
    city: 'Munich',
    address: 'Werner-von-Siemens-Straße 1, 80333 Munich',
    contactPerson: 'Dr. Hans-Peter Weber',
    contactEmail: 'h.weber@siemens-auto.de',
    contactPhone: '+49 89 636 00',
    website: 'https://automation.siemens.com',
    supplierStatus: 'APPROVED',
    complianceStatus: 'COMPLIANT',
    riskScore: 18,
    riskLevel: 'LOW',
    riskAssessment: {
      financialScore: 15,
      operationalScore: 18,
      geopoliticalScore: 12,
      esgScore: 22,
      cyberScore: 24,
      overallScore: 18,
      level: 'LOW',
      lastAssessedDate: '2026-08-15',
      assessedBy: 'Marcus Vance (Senior Risk Assessor)',
      mitigationNotes: 'Top-tier balance sheet and robust multi-facility redundancy across the EU.',
    },
    performance: {
      qualityScore: 96,
      deliveryScore: 94,
      overallScore: 95,
      status: 'EXEMPLARY',
      lastEvaluatedDate: '2026-09-01',
      evaluationCycle: 'Q3-2026',
      onTimeDeliveryRate: 98.6,
      defectRatePpm: 45,
      notes: 'Consistently exceeds SLA thresholds for lead time and precision calibration.',
    },
    documents: [
      {
        id: 'DOC-101',
        supplierId: 'SUP-1001',
        documentType: 'ISO 9001 Quality Management',
        documentNumber: 'TUV-QM-2024-889',
        issueDate: '2024-05-10',
        expiryDate: '2027-05-10',
        status: 'VALID',
        verificationAuthority: 'TÜV SÜD Germany',
        documentName: 'ISO_9001_Cert_Siemens.pdf',
        fileSize: '2.4 MB',
      },
      {
        id: 'DOC-102',
        supplierId: 'SUP-1001',
        documentType: 'Anti-Bribery & Corruption (ISO 37001)',
        documentNumber: 'DE-ABC-99120',
        issueDate: '2025-01-14',
        expiryDate: '2027-01-14',
        status: 'VALID',
        verificationAuthority: 'BSI Group Germany',
        documentName: 'ISO_37001_AntiBribery.pdf',
        fileSize: '1.8 MB',
      },
      {
        id: 'DOC-103',
        supplierId: 'SUP-1001',
        documentType: 'ESG Sustainability Audit (EcoVadis)',
        documentNumber: 'ECO-GOLD-2025-01',
        issueDate: '2025-03-20',
        expiryDate: '2027-03-20',
        status: 'VALID',
        verificationAuthority: 'EcoVadis Rating SAS',
        documentName: 'EcoVadis_Gold_Audit.pdf',
        fileSize: '3.1 MB',
      },
      {
        id: 'DOC-104',
        supplierId: 'SUP-1001',
        documentType: 'Corporate Tax Clearance',
        documentNumber: 'FA-MUC-982103',
        issueDate: '2026-01-10',
        expiryDate: '2027-01-10',
        status: 'VALID',
        verificationAuthority: 'Finanzamt München',
        documentName: 'Finanzamt_Clearence_2026.pdf',
        fileSize: '890 KB',
      },
    ],
    purchaseOrders: [
      {
        id: 'PO-8821',
        poNumber: '4500098821',
        orderDate: '2026-09-12',
        amount: 840000,
        currency: 'EUR',
        status: 'DELIVERED',
        itemsCount: 12,
        complianceGatePassed: true,
        paymentTerms: 'Net 60',
      },
      {
        id: 'PO-9104',
        poNumber: '4500099104',
        orderDate: '2026-09-28',
        amount: 420000,
        currency: 'EUR',
        status: 'RELEASED',
        itemsCount: 6,
        complianceGatePassed: true,
        paymentTerms: 'Net 60',
      },
    ],
    annualSpend: 3450000,
    spendCurrency: 'EUR',
    paymentTerms: 'Net 60 Days',
    bankIban: 'DE89370400440532013000',
    createdAt: '2023-01-15',
    updatedAt: '2026-09-28',
    approvedBy: 'Elena Rostova (VP Procurement)',
    approvalDate: '2023-02-01',
  },
  {
    id: 'SUP-1002',
    name: 'Kyocera Precision Electronics Ltd',
    taxId: 'JP-9012345678',
    category: 'Electronic Components & Ceramics',
    country: 'Japan',
    countryCode: 'JP',
    city: 'Kyoto',
    address: '6 Takeda Tobadono-cho, Fushimi-ku, Kyoto 612-8501',
    contactPerson: 'Kenji Takahashi',
    contactEmail: 'k-takahashi@kyocera-components.jp',
    contactPhone: '+81 75 604 3500',
    website: 'https://global.kyocera.com',
    supplierStatus: 'APPROVED',
    complianceStatus: 'COMPLIANT',
    riskScore: 24,
    riskLevel: 'LOW',
    riskAssessment: {
      financialScore: 20,
      operationalScore: 22,
      geopoliticalScore: 28,
      esgScore: 25,
      cyberScore: 25,
      overallScore: 24,
      level: 'LOW',
      lastAssessedDate: '2026-07-10',
      assessedBy: 'Sarah Jenkins (Compliance Lead)',
      mitigationNotes: 'Low financial risk. Geopolitical resilience verified for Pacific rim transit routes.',
    },
    performance: {
      qualityScore: 98,
      deliveryScore: 92,
      overallScore: 95,
      status: 'EXEMPLARY',
      lastEvaluatedDate: '2026-08-20',
      evaluationCycle: 'Q3-2026',
      onTimeDeliveryRate: 97.4,
      defectRatePpm: 28,
      notes: 'Exceptional component quality with zero RMA in 2026.',
    },
    documents: [
      {
        id: 'DOC-201',
        supplierId: 'SUP-1002',
        documentType: 'ISO 9001 Quality Management',
        documentNumber: 'JQA-QM-4412',
        issueDate: '2024-06-01',
        expiryDate: '2027-06-01',
        status: 'VALID',
        verificationAuthority: 'Japan Quality Assurance Org (JQA)',
        documentName: 'JQA_ISO_9001.pdf',
        fileSize: '1.9 MB',
      },
      {
        id: 'DOC-202',
        supplierId: 'SUP-1002',
        documentType: 'Cyber Security & ISO 27001',
        documentNumber: 'BSI-ISMS-771',
        issueDate: '2025-02-10',
        expiryDate: '2028-02-10',
        status: 'VALID',
        verificationAuthority: 'BSI Asia Pacific',
        documentName: 'ISO27001_Kyocera_Audit.pdf',
        fileSize: '3.4 MB',
      },
      {
        id: 'DOC-203',
        supplierId: 'SUP-1002',
        documentType: 'RoHS & REACH Chemical Compliance',
        documentNumber: 'REACH-JP-2025-99',
        issueDate: '2025-04-18',
        expiryDate: '2026-11-15',
        status: 'EXPIRING_SOON',
        verificationAuthority: 'SGS Japan',
        documentName: 'RoHS_REACH_Certificate.pdf',
        fileSize: '1.2 MB',
      },
    ],
    purchaseOrders: [
      {
        id: 'PO-8910',
        poNumber: '4500098910',
        orderDate: '2026-08-14',
        amount: 560000,
        currency: 'USD',
        status: 'DELIVERED',
        itemsCount: 20,
        complianceGatePassed: true,
        paymentTerms: 'Net 45',
      },
    ],
    annualSpend: 2150000,
    spendCurrency: 'USD',
    paymentTerms: 'Net 45 Days',
    bankIban: 'JP1400010000000123456789',
    createdAt: '2023-04-10',
    updatedAt: '2026-08-20',
    approvedBy: 'Elena Rostova (VP Procurement)',
    approvalDate: '2023-04-20',
  },
  {
    id: 'SUP-1003',
    name: 'Rheinmetall Defense & Heavy Components',
    taxId: 'DE-122904812',
    category: 'Heavy Engineering & Defense Materials',
    country: 'Germany',
    countryCode: 'DE',
    city: 'Düsseldorf',
    address: 'Rheinmetall Platz 1, 40476 Düsseldorf',
    contactPerson: 'Wolfgang Brandt',
    contactEmail: 'w.brandt@rheinmetall-comp.de',
    contactPhone: '+49 211 473 01',
    website: 'https://rheinmetall.com',
    supplierStatus: 'UNDER_REVIEW',
    complianceStatus: 'WARNING',
    riskScore: 78,
    riskLevel: 'HIGH',
    riskAssessment: {
      financialScore: 65,
      operationalScore: 82,
      geopoliticalScore: 88,
      esgScore: 75,
      cyberScore: 80,
      overallScore: 78,
      level: 'HIGH',
      lastAssessedDate: '2026-09-18',
      assessedBy: 'David Kim (Senior Risk Officer)',
      mitigationNotes: 'High geopolitical exposure and dual-use export regulations trigger mandatory compliance committee review.',
    },
    performance: {
      qualityScore: 88,
      deliveryScore: 74,
      overallScore: 81,
      status: 'SATISFACTORY',
      lastEvaluatedDate: '2026-09-10',
      evaluationCycle: 'Q3-2026',
      onTimeDeliveryRate: 82.1,
      defectRatePpm: 180,
      notes: 'Supply delays noticed due to raw material allocation constraints in Q2/Q3.',
    },
    documents: [
      {
        id: 'DOC-301',
        supplierId: 'SUP-1003',
        documentType: 'Dual-Use Export Compliance License',
        documentNumber: 'BAFA-EXP-2025-091',
        issueDate: '2025-01-01',
        expiryDate: '2026-10-25',
        status: 'EXPIRING_SOON',
        verificationAuthority: 'Federal Office of Economics and Export Control (BAFA)',
        documentName: 'BAFA_Export_License_2025.pdf',
        fileSize: '4.5 MB',
      },
      {
        id: 'DOC-302',
        supplierId: 'SUP-1003',
        documentType: 'ISO 9001 Quality Management',
        documentNumber: 'DE-RHEIN-9001-A',
        issueDate: '2024-03-12',
        expiryDate: '2027-03-12',
        status: 'VALID',
        verificationAuthority: 'DNV GL Germany',
        documentName: 'DNV_ISO9001.pdf',
        fileSize: '2.1 MB',
      },
    ],
    purchaseOrders: [
      {
        id: 'PO-9201',
        poNumber: '4500099201',
        orderDate: '2026-09-02',
        amount: 1250000,
        currency: 'EUR',
        status: 'ON_HOLD',
        itemsCount: 4,
        complianceGatePassed: false,
        paymentTerms: 'Net 90',
      },
    ],
    annualSpend: 4800000,
    spendCurrency: 'EUR',
    paymentTerms: 'Net 90 Days',
    bankIban: 'DE12300200300123456789',
    createdAt: '2024-02-18',
    updatedAt: '2026-09-18',
  },
  {
    id: 'SUP-1004',
    name: 'Apex Logistics & Freight Global Inc',
    taxId: 'US-841920841',
    category: 'Logistics & Intermodal Freight',
    country: 'United States',
    countryCode: 'US',
    city: 'Chicago',
    address: '233 S Wacker Dr, Suite 4400, Chicago, IL 60606',
    contactPerson: 'Jessica Sterling',
    contactEmail: 'j.sterling@apex-freight-global.com',
    contactPhone: '+1 312 555 0199',
    website: 'https://apexlogistics-global.com',
    supplierStatus: 'BLOCKED',
    complianceStatus: 'NON_COMPLIANT',
    riskScore: 68,
    riskLevel: 'HIGH',
    riskAssessment: {
      financialScore: 62,
      operationalScore: 71,
      geopoliticalScore: 64,
      esgScore: 70,
      cyberScore: 73,
      overallScore: 68,
      level: 'HIGH',
      lastAssessedDate: '2026-09-22',
      assessedBy: 'Marcus Vance (Senior Risk Assessor)',
      mitigationNotes: 'Supplier blocked automatically following expiration of mandatory Anti-Bribery & Corruption certification.',
    },
    performance: {
      qualityScore: 68,
      deliveryScore: 62,
      overallScore: 65,
      status: 'NEEDS_IMPROVEMENT',
      lastEvaluatedDate: '2026-08-30',
      evaluationCycle: 'Q3-2026',
      onTimeDeliveryRate: 74.0,
      defectRatePpm: 420,
      notes: 'Severe shipping bottlenecks recorded in Midwest corridor. Customs clearance delays.',
    },
    documents: [
      {
        id: 'DOC-401',
        supplierId: 'SUP-1004',
        documentType: 'Anti-Bribery & Corruption (FCPA / ISO 37001)',
        documentNumber: 'FCPA-AUDIT-2024-88',
        issueDate: '2024-08-15',
        expiryDate: '2026-08-15',
        status: 'EXPIRED',
        verificationAuthority: 'KPMG US Compliance Services',
        documentName: 'FCPA_Audit_Report_2024.pdf',
        fileSize: '3.8 MB',
        notes: 'Expired 50 days ago. Immediate supplier freeze triggered per enterprise compliance policy.',
      },
      {
        id: 'DOC-402',
        supplierId: 'SUP-1004',
        documentType: 'Federal Transportation Safety License',
        documentNumber: 'DOT-MC-908122',
        issueDate: '2025-05-01',
        expiryDate: '2027-05-01',
        status: 'VALID',
        verificationAuthority: 'US Department of Transportation',
        documentName: 'US_DOT_License.pdf',
        fileSize: '1.4 MB',
      },
    ],
    purchaseOrders: [
      {
        id: 'PO-9310',
        poNumber: '4500099310',
        orderDate: '2026-09-15',
        amount: 310000,
        currency: 'USD',
        status: 'ON_HOLD',
        itemsCount: 15,
        complianceGatePassed: false,
        paymentTerms: 'Net 30',
      },
    ],
    annualSpend: 1890000,
    spendCurrency: 'USD',
    paymentTerms: 'Net 30 Days',
    bankIban: 'US64CHAS12345678901234',
    createdAt: '2023-06-12',
    updatedAt: '2026-09-22',
    blockReason: 'Compliance document [Anti-Bribery FCPA] expired on 2026-08-15. Auto-lock triggered.',
  },
  {
    id: 'SUP-1005',
    name: 'Foxconn Precision Foundry Corp',
    taxId: 'TW-52319082',
    category: 'Contract Electronics & PCB Assembly',
    country: 'Taiwan',
    countryCode: 'TW',
    city: 'New Taipei City',
    address: 'No. 2, Ziyou St, Tucheng District, New Taipei City 236',
    contactPerson: 'Chen Wei-Lun',
    contactEmail: 'wl.chen@foxconn-foundry.tw',
    contactPhone: '+886 2 2268 3466',
    website: 'https://foxconn.com',
    supplierStatus: 'APPROVED',
    complianceStatus: 'WARNING',
    riskScore: 42,
    riskLevel: 'MEDIUM',
    riskAssessment: {
      financialScore: 30,
      operationalScore: 40,
      geopoliticalScore: 58,
      esgScore: 45,
      cyberScore: 37,
      overallScore: 42,
      level: 'MEDIUM',
      lastAssessedDate: '2026-08-10',
      assessedBy: 'Sarah Jenkins (Compliance Lead)',
      mitigationNotes: 'Geopolitical risk elevated due to Taiwan Strait tensions, but secondary factory in Vietnam provides contingency.',
    },
    performance: {
      qualityScore: 94,
      deliveryScore: 90,
      overallScore: 92,
      status: 'EXEMPLARY',
      lastEvaluatedDate: '2026-09-15',
      evaluationCycle: 'Q3-2026',
      onTimeDeliveryRate: 96.1,
      defectRatePpm: 65,
      notes: 'Strong yield rate on high-density interconnect substrates.',
    },
    documents: [
      {
        id: 'DOC-501',
        supplierId: 'SUP-1005',
        documentType: 'ISO 9001 Quality Management',
        documentNumber: 'SGS-TW-2024-918',
        issueDate: '2024-04-10',
        expiryDate: '2027-04-10',
        status: 'VALID',
        verificationAuthority: 'SGS Taiwan Ltd',
        documentName: 'SGS_ISO9001.pdf',
        fileSize: '2.5 MB',
      },
      {
        id: 'DOC-502',
        supplierId: 'SUP-1005',
        documentType: 'Responsible Business Alliance (RBA) ESG Audit',
        documentNumber: 'RBA-VAP-2025-412',
        issueDate: '2025-03-01',
        expiryDate: '2026-10-30',
        status: 'EXPIRING_SOON',
        verificationAuthority: 'RBA Approved Audit Firm',
        documentName: 'RBA_VAP_Audit_Silver.pdf',
        fileSize: '3.6 MB',
      },
    ],
    purchaseOrders: [
      {
        id: 'PO-9412',
        poNumber: '4500099412',
        orderDate: '2026-09-20',
        amount: 2100000,
        currency: 'USD',
        status: 'RELEASED',
        itemsCount: 50,
        complianceGatePassed: true,
        paymentTerms: 'Net 60',
      },
    ],
    annualSpend: 7500000,
    spendCurrency: 'USD',
    paymentTerms: 'Net 60 Days',
    bankIban: 'TW20008000001234567890',
    createdAt: '2022-11-05',
    updatedAt: '2026-09-20',
    approvedBy: 'Elena Rostova (VP Procurement)',
    approvalDate: '2022-11-20',
  },
  {
    id: 'SUP-1006',
    name: 'Tata Consultancy & Cloud Systems',
    taxId: 'IN-27AAACT2727Q1ZW',
    category: 'IT Consulting & Enterprise Cloud',
    country: 'India',
    countryCode: 'IN',
    city: 'Mumbai',
    address: 'TCS House, Raveline Street, Fort, Mumbai 400001',
    contactPerson: 'Rajesh Subramanian',
    contactEmail: 'r.subramanian@tcs-enterprises.in',
    contactPhone: '+91 22 6778 9999',
    website: 'https://tcs.com',
    supplierStatus: 'APPROVED',
    complianceStatus: 'COMPLIANT',
    riskScore: 15,
    riskLevel: 'LOW',
    riskAssessment: {
      financialScore: 12,
      operationalScore: 15,
      geopoliticalScore: 18,
      esgScore: 16,
      cyberScore: 14,
      overallScore: 15,
      level: 'LOW',
      lastAssessedDate: '2026-09-05',
      assessedBy: 'David Kim (Senior Risk Officer)',
      mitigationNotes: 'Pristine credit rating, robust SOC 2 Type II controls, and global SOC redundancy.',
    },
    performance: {
      qualityScore: 92,
      deliveryScore: 96,
      overallScore: 94,
      status: 'EXEMPLARY',
      lastEvaluatedDate: '2026-09-12',
      evaluationCycle: 'Q3-2026',
      onTimeDeliveryRate: 98.9,
      defectRatePpm: 15,
      notes: 'Exceptional project milestone adherence on S/4HANA cloud migration stream.',
    },
    documents: [
      {
        id: 'DOC-601',
        supplierId: 'SUP-1006',
        documentType: 'SOC 2 Type II Security Report',
        documentNumber: 'EY-SOC2-2026-IND',
        issueDate: '2026-02-01',
        expiryDate: '2027-02-01',
        status: 'VALID',
        verificationAuthority: 'Ernst & Young LLP',
        documentName: 'TCS_SOC2_Type_II.pdf',
        fileSize: '5.2 MB',
      },
      {
        id: 'DOC-602',
        supplierId: 'SUP-1006',
        documentType: 'ISO 27001 Information Security',
        documentNumber: 'BSI-ISMS-IND-9092',
        issueDate: '2025-06-15',
        expiryDate: '2028-06-15',
        status: 'VALID',
        verificationAuthority: 'BSI India',
        documentName: 'ISO_27001_Certificate.pdf',
        fileSize: '2.3 MB',
      },
      {
        id: 'DOC-603',
        supplierId: 'SUP-1006',
        documentType: 'GDPR / DPA Compliance Validation',
        documentNumber: 'EU-DPA-TCS-2025',
        issueDate: '2025-05-10',
        expiryDate: '2027-05-10',
        status: 'VALID',
        verificationAuthority: 'Deloitte Legal Germany',
        documentName: 'GDPR_Data_Processing_Agreement.pdf',
        fileSize: '1.7 MB',
      },
    ],
    purchaseOrders: [
      {
        id: 'PO-9520',
        poNumber: '4500099520',
        orderDate: '2026-09-01',
        amount: 980000,
        currency: 'USD',
        status: 'DELIVERED',
        itemsCount: 8,
        complianceGatePassed: true,
        paymentTerms: 'Net 30',
      },
    ],
    annualSpend: 3100000,
    spendCurrency: 'USD',
    paymentTerms: 'Net 30 Days',
    bankIban: 'IN02001100000123456789',
    createdAt: '2023-01-20',
    updatedAt: '2026-09-12',
    approvedBy: 'Elena Rostova (VP Procurement)',
    approvalDate: '2023-02-10',
  },
  {
    id: 'SUP-1007',
    name: 'Schneider Energy & Power Controls',
    taxId: 'FR-4491209381',
    category: 'Electrical Switchgear & Energy Management',
    country: 'France',
    countryCode: 'FR',
    city: 'Rueil-Malmaison',
    address: '35 Rue Joseph Monier, 92500 Rueil-Malmaison',
    contactPerson: 'Camille Dubois',
    contactEmail: 'c.dubois@se-controls.fr',
    contactPhone: '+33 1 41 29 70 00',
    website: 'https://se.com',
    supplierStatus: 'APPROVED',
    complianceStatus: 'COMPLIANT',
    riskScore: 36,
    riskLevel: 'MEDIUM',
    riskAssessment: {
      financialScore: 32,
      operationalScore: 35,
      geopoliticalScore: 28,
      esgScore: 48,
      cyberScore: 37,
      overallScore: 36,
      level: 'MEDIUM',
      lastAssessedDate: '2026-07-28',
      assessedBy: 'Sarah Jenkins (Compliance Lead)',
      mitigationNotes: 'Low financial risk. Moderate raw copper price exposure tracked in commodity hedging.',
    },
    performance: {
      qualityScore: 89,
      deliveryScore: 85,
      overallScore: 87,
      status: 'EXEMPLARY',
      lastEvaluatedDate: '2026-08-18',
      evaluationCycle: 'Q3-2026',
      onTimeDeliveryRate: 91.2,
      defectRatePpm: 88,
      notes: 'High reliability in high-voltage breakers and smart metering equipment.',
    },
    documents: [
      {
        id: 'DOC-701',
        supplierId: 'SUP-1007',
        documentType: 'ISO 14001 Environmental Management',
        documentNumber: 'AFNOR-ENV-2024-110',
        issueDate: '2024-09-12',
        expiryDate: '2027-09-12',
        status: 'VALID',
        verificationAuthority: 'AFNOR Certification France',
        documentName: 'AFNOR_ISO14001.pdf',
        fileSize: '2.2 MB',
      },
      {
        id: 'DOC-702',
        supplierId: 'SUP-1007',
        documentType: 'CE Conformity & Safety Declaration',
        documentNumber: 'CE-EU-SCH-2025',
        issueDate: '2025-01-20',
        expiryDate: '2028-01-20',
        status: 'VALID',
        verificationAuthority: 'Bureau Veritas France',
        documentName: 'CE_Conformity_Doc.pdf',
        fileSize: '1.6 MB',
      },
    ],
    purchaseOrders: [
      {
        id: 'PO-9610',
        poNumber: '4500099610',
        orderDate: '2026-08-22',
        amount: 720000,
        currency: 'EUR',
        status: 'DELIVERED',
        itemsCount: 18,
        complianceGatePassed: true,
        paymentTerms: 'Net 45',
      },
    ],
    annualSpend: 2600000,
    spendCurrency: 'EUR',
    paymentTerms: 'Net 45 Days',
    bankIban: 'FR76300020055012345678901',
    createdAt: '2023-08-14',
    updatedAt: '2026-08-22',
    approvedBy: 'Elena Rostova (VP Procurement)',
    approvalDate: '2023-09-01',
  },
  {
    id: 'SUP-1008',
    name: 'Valero Chemical Reagents SA',
    taxId: 'CH-190284712',
    category: 'Specialty Chemicals & Solvents',
    country: 'Switzerland',
    countryCode: 'CH',
    city: 'Basel',
    address: 'Schwarzwaldallee 215, 4058 Basel',
    contactPerson: 'Marc Zimmermann',
    contactEmail: 'm.zimmermann@valero-reagents.ch',
    contactPhone: '+41 61 688 1111',
    website: 'https://valerochemicals.ch',
    supplierStatus: 'BLOCKED',
    complianceStatus: 'NON_COMPLIANT',
    riskScore: 84,
    riskLevel: 'HIGH',
    riskAssessment: {
      financialScore: 78,
      operationalScore: 88,
      geopoliticalScore: 72,
      esgScore: 92,
      cyberScore: 90,
      overallScore: 84,
      level: 'HIGH',
      lastAssessedDate: '2026-09-25',
      assessedBy: 'David Kim (Senior Risk Officer)',
      mitigationNotes: 'Critical ESG hazardous waste handling violation reported. ISO 14001 certification expired without renewal.',
    },
    performance: {
      qualityScore: 54,
      deliveryScore: 42,
      overallScore: 48,
      status: 'CRITICAL',
      lastEvaluatedDate: '2026-09-02',
      evaluationCycle: 'Q3-2026',
      onTimeDeliveryRate: 58.0,
      defectRatePpm: 890,
      notes: 'Chemical purity discrepancies detected in Batch 402; batch rejected on dock inspection.',
    },
    documents: [
      {
        id: 'DOC-801',
        supplierId: 'SUP-1008',
        documentType: 'ISO 14001 Environmental & Hazardous Waste Cert',
        documentNumber: 'SQS-CH-ENV-2023',
        issueDate: '2023-07-15',
        expiryDate: '2026-07-15',
        status: 'EXPIRED',
        verificationAuthority: 'Swiss Association for Quality and Management Systems (SQS)',
        documentName: 'SQS_Hazardous_Waste_Cert.pdf',
        fileSize: '3.9 MB',
        notes: 'Expired 81 days ago. Supplier failed re-certification audit on wastewater treatment.',
      },
      {
        id: 'DOC-802',
        supplierId: 'SUP-1008',
        documentType: 'REACH Substance Safety Data Sheet',
        documentNumber: 'REACH-SDS-CH-88',
        issueDate: '2025-02-12',
        expiryDate: '2027-02-12',
        status: 'VALID',
        verificationAuthority: 'ECHA European Chemicals Agency',
        documentName: 'REACH_SDS_Compliance.pdf',
        fileSize: '4.1 MB',
      },
    ],
    purchaseOrders: [
      {
        id: 'PO-9701',
        poNumber: '4500099701',
        orderDate: '2026-08-30',
        amount: 450000,
        currency: 'CHF',
        status: 'ON_HOLD',
        itemsCount: 5,
        complianceGatePassed: false,
        paymentTerms: 'Net 60',
      },
    ],
    annualSpend: 1450000,
    spendCurrency: 'CHF',
    paymentTerms: 'Net 60 Days',
    bankIban: 'CH9300762011623852957',
    createdAt: '2024-01-10',
    updatedAt: '2026-09-25',
    blockReason: 'Critical ISO 14001 Environmental certificate expired on 2026-07-15. Auto-lock enforced.',
  },
  {
    id: 'SUP-1009',
    name: 'Nordic Semiconductor & Microtech',
    taxId: 'SE-5561234901',
    category: 'Semiconductors & Ultra-low Power Wireless',
    country: 'Sweden',
    countryCode: 'SE',
    city: 'Stockholm',
    address: 'Kistagången 20B, 164 40 Kista',
    contactPerson: 'Astrid Lindqvist',
    contactEmail: 'a.lindqvist@nordic-micro.se',
    contactPhone: '+46 8 505 000 00',
    website: 'https://nordicsemi.se',
    supplierStatus: 'UNDER_REVIEW',
    complianceStatus: 'COMPLIANT',
    riskScore: 22,
    riskLevel: 'LOW',
    riskAssessment: {
      financialScore: 20,
      operationalScore: 25,
      geopoliticalScore: 18,
      esgScore: 22,
      cyberScore: 25,
      overallScore: 22,
      level: 'LOW',
      lastAssessedDate: '2026-09-20',
      assessedBy: 'Marcus Vance (Senior Risk Assessor)',
      mitigationNotes: 'New supplier onboarding evaluation. Clean credit and stellar technical profile.',
    },
    performance: {
      qualityScore: 90,
      deliveryScore: 88,
      overallScore: 89,
      status: 'EXEMPLARY',
      lastEvaluatedDate: '2026-09-18',
      evaluationCycle: 'Q3-2026',
      onTimeDeliveryRate: 95.0,
      defectRatePpm: 50,
      notes: 'Initial test batches achieved 100% test bench pass rate.',
    },
    documents: [
      {
        id: 'DOC-901',
        supplierId: 'SUP-1009',
        documentType: 'ISO 9001 Quality Management',
        documentNumber: 'RISE-QM-2025-44',
        issueDate: '2025-04-10',
        expiryDate: '2028-04-10',
        status: 'VALID',
        verificationAuthority: 'RISE Research Institutes of Sweden',
        documentName: 'RISE_ISO9001_Nordic.pdf',
        fileSize: '2.0 MB',
      },
      {
        id: 'DOC-902',
        supplierId: 'SUP-1009',
        documentType: 'Conflict Minerals Free Declaration',
        documentNumber: 'RMI-CMR-2026-01',
        issueDate: '2026-01-15',
        expiryDate: '2027-01-15',
        status: 'VALID',
        verificationAuthority: 'Responsible Minerals Initiative (RMI)',
        documentName: 'Conflict_Minerals_Declaration.pdf',
        fileSize: '1.5 MB',
      },
    ],
    purchaseOrders: [],
    annualSpend: 0,
    spendCurrency: 'EUR',
    paymentTerms: 'Net 30 Days',
    bankIban: 'SE4550000000054910000003',
    createdAt: '2026-09-15',
    updatedAt: '2026-09-20',
  },
  {
    id: 'SUP-1010',
    name: 'Continental Mobility Hardware GmbH',
    taxId: 'DE-115654321',
    category: 'Automotive Sensors & Braking Systems',
    country: 'Germany',
    countryCode: 'DE',
    city: 'Hanover',
    address: 'Vahrenwalder Str. 9, 30165 Hannover',
    contactPerson: 'Klaus Fischer',
    contactEmail: 'k.fischer@continental-mobility.de',
    contactPhone: '+49 511 938 01',
    website: 'https://continental.de',
    supplierStatus: 'APPROVED',
    complianceStatus: 'WARNING',
    riskScore: 51,
    riskLevel: 'MEDIUM',
    riskAssessment: {
      financialScore: 48,
      operationalScore: 55,
      geopoliticalScore: 42,
      esgScore: 56,
      cyberScore: 54,
      overallScore: 51,
      level: 'MEDIUM',
      lastAssessedDate: '2026-08-05',
      assessedBy: 'David Kim (Senior Risk Officer)',
      mitigationNotes: 'Automotive market margin pressure noted; operational redundancy is solid.',
    },
    performance: {
      qualityScore: 82,
      deliveryScore: 80,
      overallScore: 81,
      status: 'SATISFACTORY',
      lastEvaluatedDate: '2026-09-08',
      evaluationCycle: 'Q3-2026',
      onTimeDeliveryRate: 88.5,
      defectRatePpm: 140,
      notes: 'Braking sensors meet rigorous IATF 16949 tolerances.',
    },
    documents: [
      {
        id: 'DOC-1001',
        supplierId: 'SUP-1010',
        documentType: 'IATF 16949 Automotive Quality',
        documentNumber: 'DEKRA-IATF-2024-99',
        issueDate: '2024-10-15',
        expiryDate: '2026-10-28',
        status: 'EXPIRING_SOON',
        verificationAuthority: 'DEKRA Certification GmbH',
        documentName: 'DEKRA_IATF_16949.pdf',
        fileSize: '3.1 MB',
      },
      {
        id: 'DOC-1002',
        supplierId: 'SUP-1010',
        documentType: 'TISAX Automotive Cyber Security Level 3',
        documentNumber: 'TISAX-ENX-2025-41',
        issueDate: '2025-05-20',
        expiryDate: '2028-05-20',
        status: 'VALID',
        verificationAuthority: 'ENX Association',
        documentName: 'TISAX_Level3_Report.pdf',
        fileSize: '4.8 MB',
      },
    ],
    purchaseOrders: [
      {
        id: 'PO-9810',
        poNumber: '4500099810',
        orderDate: '2026-09-18',
        amount: 890000,
        currency: 'EUR',
        status: 'RELEASED',
        itemsCount: 22,
        complianceGatePassed: true,
        paymentTerms: 'Net 60',
      },
    ],
    annualSpend: 3900000,
    spendCurrency: 'EUR',
    paymentTerms: 'Net 60 Days',
    bankIban: 'DE21250500000123456789',
    createdAt: '2023-03-01',
    updatedAt: '2026-09-18',
    approvedBy: 'Elena Rostova (VP Procurement)',
    approvalDate: '2023-03-25',
  },
  {
    id: 'SUP-1011',
    name: 'Sino-Pacific Freight Forwarding',
    taxId: 'SG-201938102G',
    category: 'Maritime Cargo & Customs Brokerage',
    country: 'Singapore',
    countryCode: 'SG',
    city: 'Singapore',
    address: '10 Collyer Quay, Ocean Financial Centre, Singapore 049315',
    contactPerson: 'Lim Boon Kiat',
    contactEmail: 'bk.lim@sinopacific-freight.sg',
    contactPhone: '+65 6832 9000',
    website: 'https://sinopacific-freight.sg',
    supplierStatus: 'REJECTED',
    complianceStatus: 'NON_COMPLIANT',
    riskScore: 72,
    riskLevel: 'HIGH',
    riskAssessment: {
      financialScore: 70,
      operationalScore: 75,
      geopoliticalScore: 78,
      esgScore: 68,
      cyberScore: 69,
      overallScore: 72,
      level: 'HIGH',
      lastAssessedDate: '2026-09-14',
      assessedBy: 'David Kim (Senior Risk Officer)',
      mitigationNotes: 'Failed sanction screening watch-list match and transparency requirements.',
    },
    performance: {
      qualityScore: 60,
      deliveryScore: 56,
      overallScore: 58,
      status: 'NEEDS_IMPROVEMENT',
      lastEvaluatedDate: '2026-09-14',
      evaluationCycle: 'Q3-2026',
      onTimeDeliveryRate: 64.0,
      defectRatePpm: 650,
      notes: 'Unexplained transshipment route alterations detected.',
    },
    documents: [
      {
        id: 'DOC-1101',
        supplierId: 'SUP-1011',
        documentType: 'Maritime Anti-Corruption Network (MACN) Cert',
        documentNumber: 'MACN-SG-2023-11',
        issueDate: '2023-08-01',
        expiryDate: '2026-08-01',
        status: 'EXPIRED',
        verificationAuthority: 'MACN Secretariat',
        documentName: 'MACN_Compliance_Cert.pdf',
        fileSize: '1.9 MB',
      },
    ],
    purchaseOrders: [],
    annualSpend: 0,
    spendCurrency: 'USD',
    paymentTerms: 'Net 30 Days',
    bankIban: 'SG90OCBC00010001234567',
    createdAt: '2026-08-20',
    updatedAt: '2026-09-14',
    rejectionReason: 'Mandatory anti-corruption clearance expired; failed international sanctions cross-check.',
  },
  {
    id: 'SUP-1012',
    name: 'SK Hynix Memory Systems Inc',
    taxId: 'KR-1208149201',
    category: 'High Bandwidth Memory (HBM) & DRAM',
    country: 'South Korea',
    countryCode: 'KR',
    city: 'Icheon',
    address: '2091 Gyeongchung-daero, Bubal-eup, Icheon-si, Gyeonggi-do',
    contactPerson: 'Min-Jun Park',
    contactEmail: 'mj.park@sk-hynix-memory.co.kr',
    contactPhone: '+82 31 630 4114',
    website: 'https://skhynix.com',
    supplierStatus: 'APPROVED',
    complianceStatus: 'COMPLIANT',
    riskScore: 28,
    riskLevel: 'LOW',
    riskAssessment: {
      financialScore: 24,
      operationalScore: 30,
      geopoliticalScore: 34,
      esgScore: 26,
      cyberScore: 26,
      overallScore: 28,
      level: 'LOW',
      lastAssessedDate: '2026-09-08',
      assessedBy: 'Sarah Jenkins (Compliance Lead)',
      mitigationNotes: 'Market leader in AI HBM3E memory. Strong investment and liquidity ratio.',
    },
    performance: {
      qualityScore: 97,
      deliveryScore: 95,
      overallScore: 96,
      status: 'EXEMPLARY',
      lastEvaluatedDate: '2026-09-22',
      evaluationCycle: 'Q3-2026',
      onTimeDeliveryRate: 99.2,
      defectRatePpm: 22,
      notes: 'Exceptional die yields for advanced server accelerator packages.',
    },
    documents: [
      {
        id: 'DOC-1201',
        supplierId: 'SUP-1012',
        documentType: 'ISO 9001 Quality Management',
        documentNumber: 'KSA-QM-9001-KR',
        issueDate: '2025-01-10',
        expiryDate: '2028-01-10',
        status: 'VALID',
        verificationAuthority: 'Korean Standards Association',
        documentName: 'KSA_ISO9001_SK.pdf',
        fileSize: '2.8 MB',
      },
      {
        id: 'DOC-1202',
        supplierId: 'SUP-1012',
        documentType: 'Corporate ESG & Carbon Footprint Audit',
        documentNumber: 'K-RE100-2025-88',
        issueDate: '2025-04-01',
        expiryDate: '2027-04-01',
        status: 'VALID',
        verificationAuthority: 'Korea Energy Agency',
        documentName: 'K_RE100_Carbon_Audit.pdf',
        fileSize: '3.3 MB',
      },
    ],
    purchaseOrders: [
      {
        id: 'PO-9920',
        poNumber: '4500099920',
        orderDate: '2026-09-24',
        amount: 3400000,
        currency: 'USD',
        status: 'RELEASED',
        itemsCount: 100,
        complianceGatePassed: true,
        paymentTerms: 'Net 60',
      },
    ],
    annualSpend: 9200000,
    spendCurrency: 'USD',
    paymentTerms: 'Net 60 Days',
    bankIban: 'KR34004000000012345678',
    createdAt: '2022-09-10',
    updatedAt: '2026-09-24',
    approvedBy: 'Elena Rostova (VP Procurement)',
    approvalDate: '2022-10-01',
  },
];

export const INITIAL_ACTIVITIES: ActivityLogItem[] = [
  {
    id: 'ACT-901',
    timestamp: '2026-10-03 16:45:22',
    supplierId: 'SUP-1004',
    supplierName: 'Apex Logistics & Freight Global Inc',
    type: 'BLOCK',
    description: 'Supplier status locked to BLOCKED: Compliance document [FCPA/ISO 37001] expired.',
    actor: 'Compliance Gatekeeper Bot (System)',
    actorRole: 'System Bot',
    severity: 'ERROR',
    previousStatus: 'APPROVED',
    newStatus: 'BLOCKED',
    reason: 'Active compliance document expired on 2026-08-15.',
    ipAddress: '10.14.88.2',
    clientTenant: 'Client 100',
  },
  {
    id: 'ACT-902',
    timestamp: '2026-10-02 14:20:10',
    supplierId: 'SUP-1008',
    supplierName: 'Valero Chemical Reagents SA',
    type: 'DOC_EXPIRY',
    description: 'Document [ISO 14001 Environmental & Hazardous Waste Cert] exceeded expiry limit. Supplier BLOCKED.',
    actor: 'Enterprise Compliance Scheduler',
    actorRole: 'System Bot',
    severity: 'ERROR',
    previousStatus: 'APPROVED',
    newStatus: 'BLOCKED',
    reason: 'SQS certification lapsed without renewal.',
    ipAddress: '10.14.88.1',
    clientTenant: 'Client 100',
  },
  {
    id: 'ACT-903',
    timestamp: '2026-10-01 11:32:00',
    supplierId: 'SUP-1003',
    supplierName: 'Rheinmetall Defense & Heavy Components',
    type: 'RISK_REASSESSMENT',
    description: 'Risk assessment recalculated. Overall Risk Score adjusted to 78 (HIGH) - mandatory review pending.',
    actor: 'David Kim (Senior Risk Officer)',
    actorRole: 'Senior Risk Officer',
    severity: 'WARNING',
    previousStatus: '54 (MEDIUM)',
    newStatus: '78 (HIGH)',
    reason: 'Updated dual-use geopolitical supply friction parameters.',
    ipAddress: '192.168.1.104',
    clientTenant: 'Client 100',
  },
  {
    id: 'ACT-904',
    timestamp: '2026-09-28 09:15:45',
    supplierId: 'SUP-1001',
    supplierName: 'Siemens Industrial Automation AG',
    type: 'APPROVAL',
    description: 'Annual compliance re-certification approved. PO #4500099104 released for processing.',
    actor: 'Elena Rostova (Chief Compliance Officer)',
    actorRole: 'Admin',
    severity: 'SUCCESS',
    previousStatus: 'UNDER_REVIEW',
    newStatus: 'APPROVED',
    reason: 'Full recertification completed with 100% green compliance gate.',
    ipAddress: '192.168.1.20',
    clientTenant: 'Client 100',
  },
  {
    id: 'ACT-905',
    timestamp: '2026-09-24 13:40:00',
    supplierId: 'SUP-1012',
    supplierName: 'SK Hynix Memory Systems Inc',
    type: 'APPROVAL',
    description: 'Purchase commitment approved: PO #4500099920 ($3,400,000) verified with green compliance gate.',
    actor: 'Elena Rostova (Chief Compliance Officer)',
    actorRole: 'Admin',
    severity: 'SUCCESS',
    previousStatus: 'PENDING_APPROVAL',
    newStatus: 'RELEASED',
    reason: 'Strategic memory die allocation release.',
    ipAddress: '192.168.1.20',
    clientTenant: 'Client 100',
  },
  {
    id: 'ACT-906',
    timestamp: '2026-09-20 17:05:12',
    supplierId: 'SUP-1009',
    supplierName: 'Nordic Semiconductor & Microtech',
    type: 'SUPPLIER_CREATED',
    description: 'New supplier dossier registered. Initial risk score calculated at 22 (LOW). Ready for review.',
    actor: 'Marcus Vance (Senior Procurement Manager)',
    actorRole: 'Procurement Manager',
    severity: 'INFO',
    previousStatus: 'NEW',
    newStatus: 'UNDER_REVIEW',
    reason: 'Initial supplier onboarding registration.',
    ipAddress: '192.168.1.45',
    clientTenant: 'Client 100',
  },
];

export const INITIAL_NOTIFICATIONS: import('../types/supplier').NotificationItem[] = [
  {
    id: 'NOTIF-1',
    category: 'EXPIRY',
    title: 'Document Expired: Anti-Bribery FCPA',
    message: 'Apex Logistics & Freight (SUP-1004) compliance certificate expired. Supplier auto-blocked per policy.',
    timestamp: '2026-10-03 16:45:22',
    isRead: false,
    severity: 'CRITICAL',
    targetUrl: '/suppliers/SUP-1004',
    supplierId: 'SUP-1004',
    supplierName: 'Apex Logistics & Freight Global Inc',
  },
  {
    id: 'NOTIF-2',
    category: 'EXPIRY',
    title: 'Expiring Soon: Dual-Use Export License',
    message: 'Rheinmetall Defense (SUP-1003) license expires in 21 days. Request renewal dossier.',
    timestamp: '2026-10-02 18:00:10',
    isRead: false,
    severity: 'WARNING',
    targetUrl: '/suppliers/SUP-1003',
    supplierId: 'SUP-1003',
    supplierName: 'Rheinmetall Defense & Heavy Components',
  },
  {
    id: 'NOTIF-3',
    category: 'HIGH_RISK',
    title: 'High Risk Exposure Alert: Score 84',
    message: 'Valero Chemical Reagents SA (SUP-1008) scored 84 (HIGH). Immediate procurement freeze enforced.',
    timestamp: '2026-10-01 11:32:00',
    isRead: false,
    severity: 'CRITICAL',
    targetUrl: '/suppliers/SUP-1008',
    supplierId: 'SUP-1008',
    supplierName: 'Valero Chemical Reagents SA',
  },
  {
    id: 'NOTIF-4',
    category: 'HIGH_RISK',
    title: 'High Risk Review Pending: Score 78',
    message: 'Rheinmetall Defense (SUP-1003) requires mandatory executive compliance committee sign-off.',
    timestamp: '2026-09-30 08:45:00',
    isRead: false,
    severity: 'WARNING',
    targetUrl: '/risk',
    supplierId: 'SUP-1003',
    supplierName: 'Rheinmetall Defense & Heavy Components',
  },
  {
    id: 'NOTIF-5',
    category: 'APPROVAL',
    title: 'Supplier Approved: Siemens AG',
    message: 'Annual compliance re-certification approved. All purchase commitments cleared for release.',
    timestamp: '2026-09-28 09:15:45',
    isRead: true,
    severity: 'SUCCESS',
    targetUrl: '/suppliers/SUP-1001',
    supplierId: 'SUP-1001',
    supplierName: 'Siemens Industrial Automation AG',
  },
  {
    id: 'NOTIF-6',
    category: 'APPROVAL',
    title: 'Purchase Order Released: $3,400,000',
    message: 'PO #4500099920 for SK Hynix Memory Systems passed automated compliance gate.',
    timestamp: '2026-09-24 13:40:00',
    isRead: true,
    severity: 'SUCCESS',
    targetUrl: '/suppliers/SUP-1012',
    supplierId: 'SUP-1012',
    supplierName: 'SK Hynix Memory Systems Inc',
  },
];

export const INITIAL_USERS: import('../types/supplier').AppUser[] = [
  {
    id: 'USR-001',
    username: 'admin',
    name: 'Elena Rostova',
    email: 'e.rostova@sap-enterprise.corp',
    employeeId: 'EMP-1001',
    role: 'ADMIN',
    department: 'Global Enterprise Risk & Compliance',
    status: 'ACTIVE',
    password: 'Admin@123',
    lastLogin: '2026-10-04 10:30:12',
    avatarColor: '#0070f2',
    createdAt: '2026-01-15 08:00:00',
  },
  {
    id: 'USR-002',
    username: 'mvance',
    name: 'Marcus Vance',
    email: 'm.vance@sap-enterprise.corp',
    employeeId: 'EMP-1002',
    role: 'PROCUREMENT_MANAGER',
    department: 'Strategic Sourcing & Vendor Management',
    status: 'ACTIVE',
    password: 'Password@123',
    lastLogin: '2026-10-04 09:15:00',
    avatarColor: '#0d7f3e',
    createdAt: '2026-02-10 09:00:00',
  },
  {
    id: 'USR-003',
    username: 'jchen',
    name: 'Julian Chen',
    email: 'j.chen@sap-enterprise.corp',
    employeeId: 'EMP-1003',
    role: 'PROCUREMENT_USER',
    department: 'Direct Materials Purchasing Operations',
    status: 'ACTIVE',
    password: 'Password@123',
    lastLogin: '2026-10-03 17:40:22',
    avatarColor: '#8b5cf6',
    createdAt: '2026-03-01 10:00:00',
  },
  {
    id: 'USR-004',
    username: 'sjenkins',
    name: 'Sarah Jenkins',
    email: 's.jenkins@sap-enterprise.corp',
    employeeId: 'EMP-1004',
    role: 'AUDITOR',
    department: 'Internal Quality & Compliance Audit',
    status: 'ACTIVE',
    password: 'Password@123',
    lastLogin: '2026-10-04 08:00:15',
    avatarColor: '#c25900',
    createdAt: '2026-03-15 11:30:00',
  },
  {
    id: 'USR-005',
    username: 'kpatel',
    name: 'Kavita Patel',
    email: 'k.patel@sap-enterprise.corp',
    employeeId: 'EMP-1005',
    role: 'PROCUREMENT_MANAGER',
    department: 'Global Sourcing & Logistics',
    status: 'PENDING_APPROVAL',
    password: 'Password@123',
    lastLogin: 'Never (Registration Pending)',
    avatarColor: '#f59e0b',
    createdAt: '2026-10-04 07:45:00',
  },
];

